### ISSUE TITLE
Search isn't functional

### ISSUE THREAD

**Issue by martydingo** [mattieserver/netbox-topology-views#12]
Hiya,

When I try searching for things, the list that appears does not appear to be searching, instead it displays the top 20 or so results.

With about 500+ sites this makes it impossible to select most of the sites we'd want to see. 

![image](https://user-images.githubusercontent.com/49862656/82145684-1b35de00-9842-11ea-9a45-bac21c40efc0.png)

**Comment by mattieserver** [comment]
should be fixed in the latest release

**Comment by martydingo** [comment]
Still not functional.

Could we please not close issues until we've confirmed they're resolved? You're just going to get a lot of duplicates otherwise.

![image](https://user-images.githubusercontent.com/49862656/82149278-8c7b8e00-984e-11ea-93ce-f301d96b4264.png)

**Comment by mattieserver** [comment]
Have you cleared your browser cache and ran `python3 manage.py collectstatic --no-input` ?

**Comment by martydingo** [comment]
Right, apologies, that's fixed it.
